<?php
// config/departments.php

return [
    'name' => [
        'Accounting',
        'Administration',
        'Advertising',
        'Business Development',
        'Customer Service',
        'Engineering',
        'Finance',
        'Human Resources',
        'Information Technology',
        'Legal',
        'Marketing',
        'Operations',
        'Product Management',
        'Public Relations',
        'Research and Development',
        'Sales',
        'Support',
        'Quality Assurance',
        'Training',
        'Purchasing',
        'Logistics',
        'Supply Chain',
        'Risk Management',
        'Compliance',
        'Project Management',
        'Data Analytics',
        'Design',
        'Education',
        'Healthcare',
        'Hospitality',
        'Insurance',
        'Investor Relations',
        'Media',
        'Security',
        'Software Development',
        'Telecommunications',
        'Travel',
        'Utilities',
        'Warehousing',
        'Web Development',
        'Creative',
        'Event Management',
    ],
];
